import {
  Grid3X3,
  Ship,
  Spade,
  CircleDot,
  Dice5,
  Columns3,
  Brain,
  Crown,
  Hand,
  PenLine,
  Bomb,
  HelpCircle,
} from 'lucide-react'

export const GAMES = [
  {
    id: 'tic-tac-toe',
    name: 'Tic-Tac-Toe',
    description: 'Classic X and O on a 3x3 grid. Simple yet strategic.',
    category: 'strategy',
    minPlayers: 2,
    maxPlayers: 2,
    icon: Grid3X3,
    color: 'cyan',
    hasLocalMode: true,
    hasOnlineMode: true,
  },
  {
    id: 'battleships',
    name: 'Battleships',
    description: 'Deploy your fleet and sink your opponent before they sink yours.',
    category: 'strategy',
    minPlayers: 2,
    maxPlayers: 2,
    icon: Ship,
    color: 'magenta',
    hasLocalMode: true,
    hasOnlineMode: true,
  },
  {
    id: 'poker',
    name: 'Texas Hold\'em',
    description: 'The king of card games. Bluff, bet, and outplay your opponent.',
    category: 'cards',
    minPlayers: 2,
    maxPlayers: 2,
    icon: Spade,
    color: 'purple',
    hasLocalMode: true,
    hasOnlineMode: true,
  },
  {
    id: 'blackjack',
    name: 'Blackjack',
    description: 'Get as close to 21 as you can without going bust.',
    category: 'cards',
    minPlayers: 1,
    maxPlayers: 2,
    icon: CircleDot,
    color: 'cyan',
    hasLocalMode: true,
    hasOnlineMode: true,
  },
  {
    id: 'yahtzee',
    name: 'Yahtzee',
    description: 'Roll five dice and chase the perfect combinations.',
    category: 'dice',
    minPlayers: 1,
    maxPlayers: 2,
    icon: Dice5,
    color: 'green',
    hasLocalMode: true,
    hasOnlineMode: true,
  },
  {
    id: 'connect-four',
    name: 'Connect Four',
    description: 'Drop your discs and connect four in a row to win.',
    category: 'strategy',
    minPlayers: 2,
    maxPlayers: 2,
    icon: Columns3,
    color: 'magenta',
    hasLocalMode: true,
    hasOnlineMode: true,
  },
  {
    id: 'memory',
    name: 'Memory Match',
    description: 'Flip cards and find matching pairs. Test your memory.',
    category: 'puzzle',
    minPlayers: 2,
    maxPlayers: 2,
    icon: Brain,
    color: 'purple',
    hasLocalMode: true,
    hasOnlineMode: true,
  },
  {
    id: 'checkers',
    name: 'Checkers',
    description: 'Jump and capture all opponent pieces on the board.',
    category: 'strategy',
    minPlayers: 2,
    maxPlayers: 2,
    icon: Crown,
    color: 'cyan',
    hasLocalMode: true,
    hasOnlineMode: true,
  },
  {
    id: 'rock-paper-scissors',
    name: 'Rock Paper Scissors',
    description: 'Best of 5 rounds. Choose wisely and outsmart your rival.',
    category: 'classic',
    minPlayers: 2,
    maxPlayers: 2,
    icon: Hand,
    color: 'green',
    hasLocalMode: true,
    hasOnlineMode: true,
  },
  {
    id: 'hangman',
    name: 'Hangman',
    description: 'Guess the word letter by letter before time runs out.',
    category: 'puzzle',
    minPlayers: 2,
    maxPlayers: 2,
    icon: PenLine,
    color: 'magenta',
    hasLocalMode: true,
    hasOnlineMode: true,
  },
  {
    id: 'minesweeper',
    name: 'Minesweeper',
    description: 'Clear the minefield without triggering any explosions.',
    category: 'puzzle',
    minPlayers: 1,
    maxPlayers: 2,
    icon: Bomb,
    color: 'cyan',
    hasLocalMode: true,
    hasOnlineMode: true,
  },
  {
    id: 'trivia-quiz',
    name: 'Trivia Quiz',
    description: 'Test your knowledge across science, history, geography and more.',
    category: 'trivia',
    minPlayers: 1,
    maxPlayers: 2,
    icon: HelpCircle,
    color: 'green',
    hasLocalMode: true,
    hasOnlineMode: true,
  },
]

export function getGameById(id) {
  return GAMES.find((g) => g.id === id)
}

export function getGamesByCategory(category) {
  return GAMES.filter((g) => g.category === category)
}

export const CATEGORIES = [
  { id: 'all', label: 'All Games' },
  { id: 'strategy', label: 'Strategy' },
  { id: 'cards', label: 'Cards' },
  { id: 'dice', label: 'Dice' },
  { id: 'puzzle', label: 'Puzzle' },
  { id: 'trivia', label: 'Trivia' },
  { id: 'classic', label: 'Classic' },
]
