/**
 * Short "how to play" rules per game, shown in the HowToPlay modal.
 * Keyed by game id; each language is a list of concise steps.
 */
export const GAME_RULES: Record<string, { bs: string[]; en: string[] }> = {
  'tic-tac-toe': {
    bs: [
      'Igra se na mreži 3×3.',
      'Igrači se smjenjuju stavljajući svoj znak — X ili O.',
      'Pobjeđuje ko prvi poreda tri svoja znaka u niz: vodoravno, uspravno ili dijagonalno.',
      'Ako se mreža popuni bez pobjednika — neriješeno.',
    ],
    en: [
      'Played on a 3×3 grid.',
      'Players alternate placing their mark — X or O.',
      'First to line up three of their marks — horizontally, vertically or diagonally — wins.',
      'If the grid fills with no winner, it is a draw.',
    ],
  },
  'connect-four': {
    bs: [
      'Naizmjenično ubacujete žetone u kolone — padaju na dno.',
      'Cilj je spojiti 4 svoja žetona u nizu.',
      'Niz može biti vodoravan, uspravan ili dijagonalan.',
      'Ko prvi spoji četiri — pobjeđuje.',
    ],
    en: [
      'Take turns dropping discs into columns — they fall to the bottom.',
      'The goal is to line up 4 of your discs in a row.',
      'The line can be horizontal, vertical or diagonal.',
      'First to connect four wins.',
    ],
  },
  'dots-and-boxes': {
    bs: [
      'Naizmjenično povlačite jednu ivicu između dvije tačke.',
      'Ko zatvori četvrtu stranicu kvadrata, osvaja ga — i igra ponovo.',
      'Kad se povuku sve ivice, pobjeđuje ko ima više kvadrata.',
    ],
    en: [
      'Take turns drawing one edge between two dots.',
      'Closing the fourth side of a box claims it — and you go again.',
      'When all edges are drawn, whoever owns more boxes wins.',
    ],
  },
  battleships: {
    bs: [
      'Prvo rasporediš svoju flotu — brodovi se ne smiju dodirivati.',
      'Zatim naizmjenično gađate polja na protivničkoj mreži.',
      'Pogodak otkriva dio broda; promašaj predaje potez.',
      'Ko prvi potopi sve protivničke brodove — pobjeđuje.',
    ],
    en: [
      'First place your fleet — ships may not touch each other.',
      'Then take turns firing at squares on the opponent’s grid.',
      'A hit reveals part of a ship; a miss passes the turn.',
      'First to sink all enemy ships wins.',
    ],
  },
  blackjack: {
    bs: [
      'Cilj je zbir karata što bliži 21, a da ga ne pređeš.',
      'Figure vrijede 10, a as 1 ili 11 (kako ti odgovara).',
      '“Vuci” za novu kartu ili “stani” kad si zadovoljan.',
      'Prelazak preko 21 je gubitak (bust). Djelitelj vuče do 17.',
    ],
    en: [
      'Get your card total as close to 21 as possible without going over.',
      'Face cards are 10; an ace is 1 or 11, whichever helps.',
      '“Hit” for another card or “stand” when satisfied.',
      'Going over 21 is a bust. The dealer draws to 17.',
    ],
  },
  poker: {
    bs: [
      'Svako dobije 2 skrivene karte. Praviš najbolju kombinaciju od 5 karata koristeći svoje i zajedničke karte na stolu.',
      'Prvo se postavljaju mali i veliki blind (prisilni ulozi), pa klađenje ide u smjeru kazaljke na satu.',
      'Zajedničke karte se otkrivaju u fazama: flop (3 karte), turn (1) i river (1) — uz rundu klađenja poslije svake.',
      'U svom potezu možeš: check (dalje bez uloga), call (prati ulog), raise (povećaj) ili fold (odustani).',
      'Rang kombinacija, od najjače: Royal Flush, Poker (4 iste), Ful (3+2), Boja (5 iste boje), Kenta (5 u nizu), Tris, Dva para, Par, Visoka karta.',
      'Poslije rivera ide “showdown” — najbolja ruka uzima pot. Ako svi osim jednog odustanu, on uzima pot bez otkrivanja karata.',
    ],
    en: [
      'Each player gets 2 hidden cards. You build the best 5-card hand from your cards plus the shared cards on the table.',
      'A small and big blind (forced bets) are posted first, then betting goes clockwise.',
      'Shared cards are revealed in stages: the flop (3 cards), the turn (1) and the river (1) — with a betting round after each.',
      'On your turn you can check (pass with no bet), call (match the bet), raise, or fold.',
      'Hand ranking, strongest first: Royal Flush, Four of a Kind, Full House, Flush, Straight, Three of a Kind, Two Pair, Pair, High Card.',
      'After the river comes the showdown — best hand wins the pot. If everyone else folds, the last player left wins without showing.',
    ],
  },
  'love-letter': {
    bs: [
      'Cilj je “dostaviti pismo”: eliminisati sve ostale ili imati najvišu kartu kad špil presuši.',
      'Držiš 1 kartu; u svom potezu izvučeš drugu i jednu od te dvije odigraš, uz njen efekt.',
      'Straža (1): pogodi tuđu kartu (osim Straže) — ako pogodiš, taj igrač ispada.',
      'Sveštenik (2): pogledaj tuđu ruku. Barun (3): tajno uporedi ruke s nekim — niža vrijednost ispada.',
      'Sluškinja (4): zaštićen si do svog sljedećeg poteza. Princ (5): natjeraj igrača (ili sebe) da odbaci kartu i izvuče novu.',
      'Kancelar (6): izvuci 2 karte, zadrži 1, dvije vrati na dno špila. Kralj (7): zamijeni cijelu ruku s drugim igračem.',
      'Grofica (8): MORAŠ je odbaciti ako uz nju držiš Kralja ili Princa. Princeza (9): ako je ikako odbaciš, odmah ispadaš.',
      'Špijun (0): mali bonus na kraju ako si ga jedini odigrao. Kad špil presuši, najviša karta u ruci osvaja rundu.',
      'Skupi dovoljno žetona naklonosti (osvojenih rundi) za konačnu pobjedu.',
    ],
    en: [
      'The goal is to “deliver your letter”: knock everyone else out, or hold the highest card when the deck runs out.',
      'You hold 1 card; on your turn draw a second and play one of the two for its effect.',
      'Guard (1): guess another player’s card (not a Guard) — a correct guess knocks them out.',
      'Priest (2): peek at a hand. Baron (3): secretly compare hands with someone — the lower value is out.',
      'Handmaid (4): you’re protected until your next turn. Prince (5): force a player (or yourself) to discard and draw a new card.',
      'Chancellor (6): draw 2, keep 1, put 2 back on the bottom of the deck. King (7): swap your whole hand with another player.',
      'Countess (8): you MUST discard her if you also hold the King or Prince. Princess (9): discard her for any reason and you’re out.',
      'Spy (0): a small end-of-round bonus if you alone played it. When the deck runs out, the highest card in hand wins the round.',
      'Collect enough favor tokens (won rounds) for the overall win.',
    ],
  },
  yahtzee: {
    bs: [
      'U svakom potezu bacaš 5 kockica, do 3 puta — između bacanja zadržavaš kockice koje želiš.',
      'Rezultat moraš upisati u tačno jednu još praznu kategoriju.',
      'Gornji dio (jedinice–šestice): zbir tih brojeva. Ako u gornjem dijelu skupiš 63+, dobiješ bonus od 35.',
      'Donji dio: tris i poker (4 iste) nose zbir svih kockica; ful (3+2) = 25.',
      'Mala kenta (4 u nizu) = 30; velika kenta (5 u nizu) = 40; Yahtzee (5 istih) = 50; Šansa = zbir svih.',
      'Ako kombinacija ne prolazi, moraš “žrtvovati” neku kategoriju upisom nule.',
      'Kad se sve kategorije popune, najviše ukupnih bodova pobjeđuje.',
    ],
    en: [
      'Each turn you roll 5 dice, up to 3 times — keep the dice you want between rolls.',
      'You must score the result in exactly one still-empty category.',
      'Upper section (ones–sixes): the sum of those numbers. Reach 63+ in the upper section for a 35-point bonus.',
      'Lower section: three of a kind and four of a kind score the sum of all dice; full house (3+2) = 25.',
      'Small straight (4 in a row) = 30; large straight (5 in a row) = 40; Yahtzee (5 of a kind) = 50; Chance = sum of all.',
      'If nothing fits, you must “sacrifice” a category by scoring a zero in it.',
      'When every category is filled, the highest total wins.',
    ],
  },
  memory: {
    bs: [
      'Sve karte su okrenute licem nadolje.',
      'Okreni dvije — ako su par, uzimaš ih i igraš ponovo.',
      'Ako nisu par, vraćaju se nadolje (zapamti gdje su!).',
      'Ko sakupi više parova — pobjeđuje.',
    ],
    en: [
      'All cards start face down.',
      'Flip two — if they match, you take them and go again.',
      'If they don’t match, they flip back (remember where they were!).',
      'Whoever collects more pairs wins.',
    ],
  },
  checkers: {
    bs: [
      'Figure se kreću dijagonalno naprijed po jedno polje.',
      'Preskačeš protivničku figuru da je pojedeš — uzimanje je obavezno.',
      'Na zadnjem redu figura postaje “dama” i kreće se u oba smjera.',
      'Pobjeđuje ko pojede ili blokira sve protivničke figure.',
    ],
    en: [
      'Pieces move one square diagonally forward.',
      'Jump an opponent’s piece to capture it — capturing is mandatory.',
      'Reach the last row and a piece becomes a “king”, moving both ways.',
      'Win by capturing or blocking all enemy pieces.',
    ],
  },
  'rock-paper-scissors': {
    bs: [
      'Istovremeno birate: kamen, list ili makaze.',
      'Kamen tupi makaze, makaze sijeku list, list pokriva kamen.',
      'Isti izbor — runda je neriješena.',
      'Igra se na najbolje od 5 rundi.',
    ],
    en: [
      'Both choose at once: rock, paper or scissors.',
      'Rock blunts scissors, scissors cut paper, paper covers rock.',
      'Same choice — the round is a tie.',
      'Played as best of 5 rounds.',
    ],
  },
  hangman: {
    bs: [
      'Pogađaš skrivenu riječ slovo po slovo.',
      'Svako pogrešno slovo dodaje dio vješala.',
      'Pogodi cijelu riječ prije nego se vješalo dovrši.',
      'Previše pogrešaka — gubiš.',
    ],
    en: [
      'Guess the hidden word letter by letter.',
      'Each wrong letter adds a part of the gallows.',
      'Reveal the whole word before the gallows is finished.',
      'Too many mistakes and you lose.',
    ],
  },
  minesweeper: {
    bs: [
      'Otkrivaj polja bez mina.',
      'Broj na polju govori koliko ga mina dodiruje.',
      'Označi sumnjiva polja zastavicom.',
      'Otvori sva sigurna polja da pobijediš — mina te odmah digne u zrak.',
    ],
    en: [
      'Uncover squares without mines.',
      'A number shows how many mines touch that square.',
      'Flag the squares you suspect.',
      'Clear all safe squares to win — a mine ends it instantly.',
    ],
  },
  'trivia-quiz': {
    bs: [
      'Odgovaraš na pitanja iz raznih oblasti.',
      'Svaki tačan odgovor nosi bodove.',
      'Biraš jedan od ponuđenih odgovora.',
      'Najviše bodova na kraju pobjeđuje.',
    ],
    en: [
      'Answer questions from various topics.',
      'Each correct answer scores points.',
      'Pick one of the offered answers.',
      'The highest score at the end wins.',
    ],
  },
  perudo: {
    bs: [
      'Svako baca 5 kockica skriveno, ispod čaše, i gleda samo svoje.',
      'Licitacija je tvrdnja koliko UKUPNO (kod svih igrača) ima kockica neke vrijednosti, npr. “četiri petice”.',
      'Jedinice su džokeri — broje se kao bilo koja vrijednost.',
      'U svom potezu moraš podići licitaciju: ili veći broj kockica, ili isti broj ali veće lice.',
      'Umjesto licitacije možeš viknuti “Laž!” i osporiti prethodnu — tada svi otkriju svoje kockice i broje se.',
      'Ako stvarni broj dostigne licitaciju, izazivač je pogriješio i gubi kockicu; u suprotnom, licitator gubi kockicu.',
      'Ko ostane bez kockica ispada. Zadnji igrač s kockicama pobjeđuje.',
    ],
    en: [
      'Everyone rolls 5 dice secretly, under a cup, and sees only their own.',
      'A bid claims how many dice of a value there are in TOTAL across all players, e.g. “four fives”.',
      'Ones are wild — they count as any value.',
      'On your turn you must raise the bid: either a higher quantity, or the same quantity with a higher face.',
      'Instead of bidding you can call “Liar!” to challenge the last bid — then everyone reveals and the dice are counted.',
      'If the real count meets the bid, the challenger was wrong and loses a die; otherwise the bidder loses a die.',
      'Run out of dice and you’re out. The last player with dice wins.',
    ],
  },
  'cant-stop': {
    bs: [
      'Kolone su označene brojevima 2–12. Rubne su najkraće (2 i 12 traže 3 polja), a srednja (7) je najduža.',
      'Baciš 4 kockice i složiš ih u DVA para, tj. dva zbira (npr. 3+5 i 4+6).',
      'Tim zbirovima napreduješ privremenim markerima uz kolone. U jednom potezu smiješ imati najviše 3 privremena markera.',
      'Poslije bacanja biraš nastaviti (rizik) ili “stati” i trajno spustiti napredak markera.',
      'Ako nijedan od zbirova ne možeš odigrati (nema slobodnog markera ili je kolona već osvojena) — “pucaš” i gubiš SAV napredak tog poteza.',
      'Kad marker dođe do vrha kolone, na “stani” je trajno osvajaš. Ko prvi osvoji 3 kolone pobjeđuje.',
    ],
    en: [
      'Columns are numbered 2–12. The edges are shortest (2 and 12 need 3 steps) and the middle (7) is longest.',
      'Roll 4 dice and combine them into TWO pairs, i.e. two sums (e.g. 3+5 and 4+6).',
      'Advance temporary markers up those columns. You may have at most 3 temporary markers in a turn.',
      'After a roll you choose to continue (risk it) or “stop” and lock your markers’ progress in permanently.',
      'If neither sum is playable (no free marker, or the column is already claimed) you “bust” and lose ALL of this turn’s progress.',
      'When a marker reaches the top of a column, stopping claims it permanently. First to claim 3 columns wins.',
    ],
  },
  skull: {
    bs: [
      'Svako ima 3 cvijeta i 1 lobanju. Cilj je dva puta uspješno ispuniti poziv — tad pobjeđuješ.',
      'U prvom krugu svako stavi po jedan disk licem nadolje.',
      'Zatim redom biraš: ili dodaješ još jedan svoj disk, ili otvaraš licitaciju.',
      'Licitacija = koliko cvjetova (ukupno, gledajući vrhove stekova) tvrdiš da možeš okrenuti bez lobanje. Ostali dižu ulog ili pasiraju.',
      'Najveći licitator okreće diskove — PRVO sve svoje, pa po izboru vrhove tuđih stekova.',
      'Okreneš li onoliko cvjetova koliko si obećao — osvajaš bod. Naletiš li na lobanju, ne uspijevaš i gubiš jedan svoj disk (nasumično).',
      'Prvi igrač do 2 boda pobjeđuje.',
    ],
    en: [
      'Each player has 3 flowers and 1 skull. Win by fulfilling a bid successfully twice.',
      'In the first round everyone places one disc face down.',
      'Then, in turn, you either add another of your discs, or open the bidding.',
      'A bid = how many flowers (in total, from the tops of the stacks) you claim you can flip without a skull. Others raise or pass.',
      'The highest bidder flips discs — FIRST all of their own, then chosen tops of others’ stacks.',
      'Flip as many flowers as you promised and you score a point. Hit a skull and you fail, losing one of your discs at random.',
      'The first player to 2 points wins.',
    ],
  },
  coup: {
    bs: [
      'Svako počinje s 2 skrivena uticaja (karte likova) i 2 novčića. Kad izgubiš oba uticaja, ispadaš; zadnji preživjeli pobjeđuje.',
      'Osnovne akcije (bez lika): Prihod (+1 novčić), Strana pomoć (+2) i Coup (platiš 7, biraš protivnika da izgubi uticaj).',
      'Ako imaš 10+ novčića, u svom potezu MORAŠ izvesti Coup.',
      'Akcije likova — možeš i blefirati da imaš lika: Vojvoda uzima porez (+3); Ubica ubija (platiš 3, meta gubi uticaj); Kapetan krade 2 novčića; Ambasador mijenja svoje karte iz špila.',
      'Blokade: Vojvoda blokira Stranu pomoć; Grofica blokira ubistvo; Kapetan ili Ambasador blokiraju krađu.',
      'Izazov: kad neko tvrdi lika (za akciju ili blokadu), svako može reći “izazivam!”.',
      'Ako je blefirao, gubi uticaj. Ako je stvarno imao lika, izazivač gubi uticaj — a lik se zamijeni novom kartom iz špila.',
    ],
    en: [
      'Each player starts with 2 hidden influences (character cards) and 2 coins. Lose both influences and you’re out; last player standing wins.',
      'Basic actions (no character): Income (+1 coin), Foreign Aid (+2), and Coup (pay 7, pick an opponent to lose an influence).',
      'With 10+ coins you MUST Coup on your turn.',
      'Character actions — bluffing allowed: Duke takes tax (+3); Assassin assassinates (pay 3, target loses an influence); Captain steals 2 coins; Ambassador swaps its cards from the deck.',
      'Blocks: Duke blocks Foreign Aid; Contessa blocks assassination; Captain or Ambassador block stealing.',
      'Challenge: when someone claims a character (for an action or a block), anyone can say “I challenge!”.',
      'If they bluffed, they lose an influence. If they truly held the character, the challenger loses one — and the card is swapped for a new one from the deck.',
    ],
  },
  'six-nimmt': {
    bs: [
      'Ima 4 reda, svaki počinje jednom kartom. Svi igrači ISTOVREMENO biraju po jednu kartu iz ruke.',
      'Karte se zatim otkrivaju i slažu redom od najmanje prema najvećoj.',
      'Svaka karta ide na kraj onog reda čija je zadnja karta najbliži MANJI broj od nje.',
      'Ako bi tvoja karta bila 6. u redu, ne slaže se — “pokupiš” svih 5 karata iz tog reda, a tvoja započinje novi.',
      'Ako je tvoja karta manja od svih zadnjih karata u redovima, moraš uzeti cijeli jedan red (po izboru), a tvoja ga karta započinje iznova.',
      'Volovske glave su kazneni bodovi: 55 nosi 7 glava, višekratnici 11 → 5, desetice → 3, petice → 2, ostalo → 1.',
      'Kad neko pređe 66 kaznenih bodova, igra staje — pobjeđuje ko ima NAJMANJE volovskih glava.',
    ],
    en: [
      'There are 4 rows, each starting with one card. All players pick a card from hand at the SAME time.',
      'Cards are then revealed and placed in order from lowest to highest.',
      'Each card goes at the end of the row whose last card is the closest number SMALLER than it.',
      'If your card would be the 6th in a row, it isn’t placed — you “scoop” all 5 cards in that row, and yours starts a new one.',
      'If your card is lower than every row’s last card, you must take a whole row (your choice), and your card starts it fresh.',
      'Bull heads are penalty points: 55 is worth 7, multiples of 11 → 5, multiples of 10 → 3, multiples of 5 → 2, everything else → 1.',
      'When someone passes 66 penalty points the game ends — the player with the FEWEST bull heads wins.',
    ],
  },
  'flip-7': {
    bs: [
      'Na svom potezu vučeš karte s brojevima (0–12) i sabiraš njihove vrijednosti.',
      'Izvučeš li broj koji već imaš u ovom krugu — “pucaš” (bust) i gubiš sve bodove tog kruga.',
      'Karta “Druga šansa” te spašava od jednog busta (poništi duplikat) i ostaješ u igri.',
      'Akcijske karte: “Zamrzni” natjera igrača da odmah upiše bodove i završi krug; “Okreni tri” ga natjera da povuče 3 karte zaredom.',
      'Modifikatori (+2 do +10) dodaju bodove, a “×2” udvostručuje zbir tvojih brojeva u tom krugu.',
      'Skupiš li 7 RAZLIČITIH brojeva — to je “Flip 7”: +15 bonusa i krug se odmah završava.',
      '“Stani” na vrijeme da sačuvaš skupljene bodove kruga. Prvi igrač do 200 ukupnih bodova pobjeđuje.',
    ],
    en: [
      'On your turn you draw number cards (0–12) and add up their values.',
      'Draw a number you already have this round and you “bust”, losing all of that round’s points.',
      'A “Second Chance” card saves you from one bust (cancels the duplicate) and you stay in.',
      'Action cards: “Freeze” forces a player to bank immediately and end their round; “Flip Three” forces them to draw 3 cards in a row.',
      'Modifiers (+2 to +10) add points, and “×2” doubles the sum of your numbers that round.',
      'Collect 7 DIFFERENT numbers for a “Flip 7”: +15 bonus and the round ends at once.',
      '“Stay” in time to bank the round’s points. The first player to 200 total points wins.',
    ],
  },
  trio: {
    bs: [
      'Špil su brojevi 1–12, svaki po tri puta. Na početku svako dobije ruku karata (poredanih), a nekoliko ide u sredinu licem nadolje.',
      'Cilj je skupljati “trije” — tri iste karte (npr. tri sedmice).',
      'U svom potezu otkrivaš karte jednu po jednu: ili NAJNIŽU/NAJVIŠU kartu iz bilo čije ruke, ili neku kartu iz sredine.',
      'Vidiš samo krajnje (najnižu i najvišu) karte tuđih ruku — sredina je skrivena dok je ne otvoriš, pa pomaže i pamćenje.',
      'Prva otkrivena karta određuje broj koji loviš. Dok se sljedeće poklapaju, nastavljaš; tri iste čine trio koji uzimaš.',
      'Čim otkriješ kartu koja se ne poklapa, potez ti se prekida i sve otkrivene karte se vraćaju (u ruke ili se okrenu nadolje).',
      'Jednostavan mod: prvi do 3 tria pobjeđuje. Zgrabiš li trio sedmica (tri 7), odmah pobjeđuješ — u oba moda.',
      'Ljuti mod: pobjeđuješ s dva “povezana” tria — brojevi čiji je zbir 7 ili razlika 7 (npr. 2 se veže s 5 i s 9).',
    ],
    en: [
      'The deck is numbers 1–12, three of each. At the start each player gets a hand (kept sorted) and several cards go face down in the middle.',
      'The goal is to collect “trios” — three of the same number (e.g. three 7s).',
      'On your turn you reveal cards one at a time: either the LOWEST/HIGHEST card of any player’s hand, or a card from the middle.',
      'You only ever see the end (lowest and highest) cards of others’ hands — the middle stays hidden until flipped, so memory helps.',
      'The first card revealed sets the number you’re hunting. While the next ones match, keep going; three of a kind is a trio you keep.',
      'The moment you reveal a card that doesn’t match, your turn ends and every revealed card goes back (to hands or face down).',
      'Simple mode: first to 3 trios wins. Grab the 7-trio (three 7s) and you win instantly — in either mode.',
      'Spicy mode: win with two “connected” trios — numbers whose sum is 7 or whose difference is 7 (e.g. 2 connects to 5 and to 9).',
    ],
  },
}
